<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PLCFlow.Compiler/PLCFlow.Compiler.csproj" />
    <ProjectReference Include="../PLCFlow.Runtime/PLCFlow.Runtime.csproj" />
  </ItemGroup>
</Project>
